Add HTTP response to logger to help debug failed requests
StackStorm-Exchange/stackstorm-salt pull request #21
Opened 2021-07-20 20:14 UTC by bmarick

Salt API does not return JSON for unauthorized access. 
Adding the HTTP Status Code to the logger at the debug level.
This allows for an improved debugging experience

2021-07-20 20:24 UTC, bmarick commented
Resolves issue #22

2021-07-21 14:00 UTC, nmaludy requested changes
@bmarick can you please bump `version:` in `pack.yaml` to `1.0.1` https://github.com/StackStorm-Exchange/stackstorm-salt/blob/master/pack.yaml#L9

Also, can you please add an entry to `CHANGES.md`? https://github.com/StackStorm-Exchange/stackstorm-salt/blob/master/CHANGES.md

Thanks!

2021-07-21 21:24 UTC, bmarick commented
On it! Thank for the quick reply

2021-07-28 20:29 UTC, bmarick commented
@nmaludy is there anything else you would like me to update?

2021-07-28 20:34 UTC, nmaludy approved these changes

2021-07-28 20:34 UTC, merged

2021-07-28 20:34 UTC, nmaludy commented
@bmarick nope, sorry didn't see you updated the PR, merged.